import config from '../../../config/index.js';
import { createNotification } from '../../../helpers/api/notifications.js';

export default async ({ logger, payload }) => {
    const {
        to,
        admin_fname,
        admin_lname,
        teacher_full_name,
        link,
        subject_name,
        section_name,
        quarter,
        remark,
    } = payload;
    const expectedFields = ['to', 'admin_fname', 'admin_lname', 'teacher_full_name', 'link', 'subject_name', 'section_name', 'quarter', 'remark'];
    const hasAllFields = expectedFields.every((key) => key in payload);
    if (!hasAllFields) {
        logger.info('Lacking required fields');
        return [];
    }
    const notifications = [];

    const content = `
        <p>Dear ${admin_fname} ${admin_lname},</p>

        <p>
            This is an automated notification generated by the MNHS Student Record System.<br/>
            Your verification is needed for the grade submission of the subject "${subject_name}".
        </p>
        
        <span><strong>Teacher:</strong> ${teacher_full_name}</span><br/>
        <span><strong>Section:</strong> ${section_name}</span><br/>
        <span><strong>Subject:</strong> ${subject_name}</span><br/>
        <span><strong>Quarter:</strong> ${quarter}</span><br/>
        <span><strong>Remarks:</strong> ${remark}</span><br/>
        <span>
            <strong>URL:</strong>
            <a href=${link}>
                ${link}
            </a>
        </span><br/><br/>
        
        <span>Regards,</span><br/>
        <span><em>MNHS Student Record System</em></span>
    `;

    const notification = await createNotification({
        notification: {
            channel: 'email',
            type: 'grade_submission',
            to,
            from: config.smtp.from,
            subject: 'Grade Submission',
            content,
        },
    });

    notifications.push(notification);

    return notifications;
};
